### ISSUE TITLE
Need for a separate branch for backend

### ISSUE THREAD

**Issue by Lonewolf230** [ValscoTech/NoteSwap#5]
We need a separate branch for backend to be created in the repo. We dont have the permissions to do so ourselves so please create one

**Comment by TechAlhan826** [comment]
![image](https://github.com/user-attachments/assets/2977ec43-f3d5-4918-a0ce-e189a5be35a2)
![image](https://github.com/user-attachments/assets/b709b632-329d-4db4-8de7-00cac24bdb00)

Hi Team,

I've created a backend branch in my forked repository that includes the latest updates and fixes related to the backend. Could you please add this branch to the main repository? I've ensured that all changes are properly committed and tested.

Thanks!

@ValscoTech @dk-a-dev @krishna-kenny

**Comment by dk-a-dev** [comment]
Sure will take a look n merge to backend-dev

**Comment by dk-a-dev** [comment]
Created plz make ur PR to that branch 
I am closing the issue
